### ISSUE TITLE
Provide callback for configuring line elements

### ISSUE THREAD

**Issue by vjpr** [alex-e-leon/print-tree#4]
Use case: I want to make them grey colored.

**Comment by alex-e-leon** [comment]
@vjpr print-tree already supports this use-case - but maybe the documentation could be more explicit - if you have any suggestions to improve it please let me know or feel free to make a PR to update the docs.

the printNode argument can either take a function that takes a node and returns the string representation for that node - OR for your use case, can take the node + the branch graphic and return nothing - which lets you customise the output. So for example, if you passed the following to printNode

```
(node, branchGraphic) => { console.log(`${branchGraphic} ${chalk.grey(node.name)}`); }
```

that should achieve the result you are looking for.
